name: Generate Snake Animation

on:
  schedule: # Ejecuta la acción diariamente
    - cron: "0 20 * * *"
  workflow_dispatch: # Permite ejecutar la acción manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: JefersonDominguez
          outputs: dist/snake.svg

      - name: Push the generated Snake
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
